### ISSUE TITLE
Profile tag filters or'd with user tag filters

### ISSUE THREAD

**Issue by kcormier** [skavanagh/EC2Box#21]
Users get access to boxes that should be filtered out based on their profile.

steps to reproduce:
1) create 3 boxes in AWS named 'DEV', 'STG', and 'PRD'
2) set up a profile with filter 'Name=DEV,Name=STG' and assign it to a user.
3) As that user, do a search for 'Name=STG,Name=PRD'.

Expected Behavior:
You should only see the box STG.

Actual Behavior:
You see all 3 boxes.

My understanding is that the logic should be:

```(Profile1_Filter OR Profile2_Filter OR ... ProfileN_Filter) AND User_Filter.```

**Comment by skavanagh** [comment]
It's not perfect! If the filter tag doesn't match what is in the profile, it will still pull back the systems in the profile.
