### ISSUE TITLE
Is there a way to increase the Connection Pool size?

### ISSUE THREAD

**Issue by pramodb** [skavanagh/EC2Box#25]
Hi,

We were facing issues with the connection pool that is created to talk to the H2 db. Looks like the pool size is hard coded to be 25 and given our user base we are constantly having login issues where the app complains with the following exception :

Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1134)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	... 98 more
java.lang.NullPointerException
org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object

We use the release tar to install the app and given that these parameters are not coming from a config file we wanted to check if there is a way to increase the pool size without having to build from source.

Thanks,
Pramod.

**Comment by skavanagh** [comment]
Yes - I should make that configurable.  I've got to update some dependencies soon anyway.

**Comment by pramodb** [comment]
Hi,
Thanks for the quick response. Will try to work on generating a patch commit to make some these configs externalized, at least the database bit. 

Thanks,
Pramod.
