### ISSUE TITLE
Connection timeout issue

### ISSUE THREAD

**Issue by 0x4D31** [skavanagh/EC2Box#27]
My colleague reported a bug to me, and I just reproduced the problem: We found that after 60 seconds of inactivity, the SSH connection is disconnecting, and then the web based terminal locks and doesn't accept any inputs. After that, opening a new terminal to any host results in a blank terminal, even though I can see that the new underlying SSH connection has been made - it sits idle with no way to receive input from the terminal. I suppose they'll time out on the server after a while and be closed down, but they don't seem to have the same 60-second idle timeout!

**Comment by skavanagh** [comment]
I added this as a config option to my other project..just forgot to bring it over.

**Comment by 0x4D31** [comment]
Cool. Thanks for the great tool!

**Comment by 0x4D31** [comment]
Cool. Thanks for your quick response.

I compiled and tested it with different serverAliveIntervals (60, 40, ..). It's strange but the idle connections are again disconnected after a minute! any thoughts? 

```
[ec2-user@something ~]$ w
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT
ec2-user pts/1    somethingelse    04:39    6.00s  0.02s  0.00s w
ec2-user pts/2    ip-ec2box            05:00    1:01   0.00s  0.00s -bash

[ec2-user@something ~]$ w
USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT
ec2-user pts/1    somethingelse   04:39    0.00s  0.02s  0.00s w
```

**Comment by skavanagh** [comment]
I'll try and recreate again!

**Comment by 0x4D31** [comment]
Let me know if you need help for testing or something. Thanks.

**Comment by skavanagh** [comment]
What does your /etc/ssh/sshd_config look like??
Do you have anything for ClientAliveInterval or ClientAliveCountMax??

**Comment by 0x4D31** [comment]
I don't see anything special in my config file. It's almost like a default one. Just saw this, which should be the default:  #TCPKeepAlive yes
No. Before I report the issue, I changed that to see if it can solve the problem. But now it's the default config and both are disabled.

**Comment by skavanagh** [comment]
It could be the websocket connection that's timing out, especially if you see the SSH connections open on the box.  I've got it set to not timeout by default.  https://github.com/skavanagh/EC2Box/blob/master/src/main/resources/EC2BoxConfig.properties#L28 
Is there anything else in play??? like a reverse-proxy?? I think things like nginx have settings to timeout websockets http://nginx.org/en/docs/http/websocket.html

**Comment by 0x4D31** [comment]
I don't think it relates to the websocket connection, because as I
mentioned in the first post, I see the SSH connection is disconnecting on
the box.
Anyway, I use AWS ELB (load balancer) in front of it. Just for making sure,
I'll test it again without the ELB and get back to you.

**Comment by skavanagh** [comment]
The ELB has this timeout too that you may want to try https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/

**Comment by 0x4D31** [comment]
Yep, that's it. I changed the ELB's timeout setting.
Thanks so much Sean.
