### ISSUE TITLE
ec2Box DB password.

### ISSUE THREAD

**Issue by pramodb** [skavanagh/EC2Box#28]
Hi @skavanagh,

In our current setup the H2DB has grown beyond 7GB of size due to Audit Logging being enabled. This is causing the Audit Session screen load very slowly. We tried reducing the "deleteAuditLogAfter" from 90 to 30, and after that the Screen does not even load as it is not able to delete the older entries from the db.

I was then trying to connect to the DB using the H2DB Shell utility to see if i could flush the audit entries directly, however looks like the DB is encrypted and wanted to check with you what the default key is for decrypting it. 

Pramod.

**Comment by pramodb** [comment]
Hi, 

I was able to login to the DB from the shell. Was giving the wrong URL earlier.

**Comment by skavanagh** [comment]
Auditing can have issues if there is a lot of data in the session. Alternately, instead of using the auditing in the app, in logging utility configuration you could add an appender to send the audit logs to a logging server (such as logstash).  I've got an example commented out.

https://github.com/skavanagh/EC2Box/blob/master/src/main/resources/log4j.xml#L13-L36

**Comment by pramodb** [comment]
Hi @skavanagh ,

Thanks for the tip. We have moved to using the audit logs instead of in app auditing now.

Thanks,
Pramod.

**Comment by preetampatil3d** [comment]
Hello @pramodb & @skavanagh 

I am also facing same type of DB issues and planning to use **audit logs**. Can you please tell  me how can i achieve **audit logging**.

Thanks.

**Comment by dlethin** [comment]
This is a pretty old thread, but @pramodb do you recall the command you use to run the h2db shell?  I'm trying to run this on an old installation and I can't figure out the default password.  It's possible there is none and maybe I'm not specifying the correct jdbc URL.  Thanks.
