### ISSUE TITLE
Anti-CSRF token

### ISSUE THREAD

**Issue by caglar84** [skavanagh/EC2Box#39]
An unique anti-CSRF token should be generated and included to all POST requests and that token should be invalidated after it is used to prevent replay attacks.

The anti-CSRF tokens should be tied to the user session, and be invalidated after the user session is ended. In the case of long-lasting sessions, the anti-CSRF tokens should also have a shorter timeout.

**Comment by skavanagh** [comment]
Thinking about doing something like this https://github.com/skavanagh/EC2Box/commit/356f8fdadd8a1ae4b9df40c15a63d14a7c1d1fa5

put it on a branch for now (need to test some more)

**Comment by skavanagh** [comment]
That probably won't work though. I would have to restrict the protected action methods to only do POST

**Comment by caglar84** [comment]
I will give a try to org.apache.struts2.interceptor.TokenSessionStoreInterceptor.
