### ISSUE TITLE
Version 0.30 logging dependencies

### ISSUE THREAD

**Issue by caglar84** [skavanagh/EC2Box#48]
I just upgraded to 0.30 and I got 2 logging errors for log4j-core and log4j2.xml.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. 

Here are the workarounds to resolve them:
*Manually download log4j and copy log4j-core to lib:
cp /tmp/log4j-core-2.7.jar jetty/ec2box/WEB-INF/lib/
*Copy log4j2.xml to classes:
cp jetty/modules/log4j2-impl/resources/log4j2.xml jetty/ec2box/WEB-INF/classes/

**Comment by skavanagh** [comment]
Ah.. yes!! I updated the logger but forgot about the descriptor.  It should be the same as
https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/log4j2.xml
but replace 'keybox' with 'ec2box'

I'll take care of it tonight.

**Comment by skavanagh** [comment]
Thanks @caglar84 !!

**Comment by caglar84** [comment]
Thanks for prompt action Sean 👍
