### ISSUE TITLE
Create SSH Terminals hidden

### ISSUE THREAD

**Issue by khlumzeemee** [skavanagh/EC2Box#50]
Hi,
I noticed that the `Create SSH terminal` button is hidden when there are many servers in the list.
The reason is that it is located inside the `scrollWrapper` div, whereas ideally it should be located outside of it.
A simple change in the JSP should be sufficient, I can create a pull request for this if you agree that it will improve usability.
Cheers
Allen

**Comment by skavanagh** [comment]
Thanks Allen!  should be fixed

**Comment by khlumzeemee** [comment]
Thanks to you! 😊 I'll check it out and keep you updated.
