### ISSUE TITLE
Cannot Delete Users...

### ISSUE THREAD

**Issue by charliejones** [skavanagh/EC2Box#56]
When I attempt to delete a user from EC2Box, I immediately get logged out. The following message is then logged:
`2017-05-24 16:48:10.706:INFO:oejs.session:qtp428746855-9: Session node0726rajz2qo191gb6tiw6hzo3n0 already being invalidated`

Upon logging back into EC2Box, the user is still there. I've tried deleting multiple users and it's always the same result.

EC2Box v0.30.03
Java 8
Ubuntu 16.04

**Comment by skavanagh** [comment]
Looks like it's missing the CSRF token

**Comment by skavanagh** [comment]
Thanks!
