### ISSUE TITLE
Promoting a user to Full Access retains original assigned profiles

### ISSUE THREAD

**Issue by dlethin** [skavanagh/EC2Box#62]
While troubleshooting why a particular user could not access some boxes in ec2box, we escallated the user to "Full Access".  It did not resolve his problem.  We later realized the problem was that the tags we had for the profile he was assigned to needed to be updated and we fixed the problem.

So we then changed the user back to "Admin Access Only".  It was then that we noticed that the profiles originally assigned to him were still present.

So it seems the bug is that if a user is marked as "Full Access", but they have Profiles Associated with them, the Profiles take Precedence and limit his access.   I would think if someone is Full Access, then there Profile tags would be ignored and then would get access to everything.  Because if a user is marked a "Full Access", then the "Assign Profiles button dissapears" and you can't make changes.

**Comment by skavanagh** [comment]
Thanks - I'll take look. Sounds like a bug. Im sure that logic is not expecting "Full Access" users to have profiles. You should be able to switch the user type back and remove the profiles (deleting the user should remove them too)
